from __future__ import annotations

from random import choice, randint


FAKE_USERS = [
    {"id": 1, "username": "admin", "role": "superuser", "mfa": "enabled", "last_login": "2026-05-21T19:20:10Z"},
    {"id": 2, "username": "backup_svc", "role": "service", "mfa": "exempt", "last_login": "2026-05-20T03:11:42Z"},
    {"id": 3, "username": "finance.ops", "role": "analyst", "mfa": "enabled", "last_login": "2026-05-22T08:47:02Z"},
    {"id": 4, "username": "root", "role": "disabled", "mfa": "disabled", "last_login": "2026-04-12T02:04:55Z"},
]

FAKE_FILES = [
    {"name": "customer_export_2026_05.csv", "path": "/var/backups/customer_export_2026_05.csv", "size": "184 MB"},
    {"name": "prod-db.env", "path": "/srv/app/releases/current/.env", "size": "4 KB"},
    {"name": "vpn_users.xlsx", "path": "/home/admin/share/vpn_users.xlsx", "size": "91 KB"},
    {"name": "ledger_snapshot.sql.gz", "path": "/mnt/backup/ledger_snapshot.sql.gz", "size": "2.7 GB"},
    {"name": "ssh_keys_old.zip", "path": "/opt/archive/ssh_keys_old.zip", "size": "36 KB"},
]

FAKE_TABLES = [
    {
        "table": "users",
        "rows": 48231,
        "columns": ["id", "email", "password_hash", "mfa_secret", "last_login_at"],
    },
    {
        "table": "payments",
        "rows": 128904,
        "columns": ["id", "customer_id", "card_last4", "amount", "status"],
    },
    {
        "table": "api_keys",
        "rows": 87,
        "columns": ["id", "owner", "token_prefix", "scope", "rotated_at"],
    },
    {
        "table": "admin_audit_log",
        "rows": 9412,
        "columns": ["id", "actor", "action", "ip_address", "created_at"],
    },
]

FAKE_BACKUPS = [
    {"file": "daily-prod-2026-05-23.tar.gz", "size": "4.8 GB", "status": "available"},
    {"file": "daily-prod-2026-05-22.tar.gz", "size": "4.7 GB", "status": "available"},
    {"file": "weekly-ledger-2026-W20.sql.gz", "size": "9.2 GB", "status": "cold-storage"},
    {"file": "identity-vault-keys-rotated.zip", "size": "212 KB", "status": "restricted"},
]


def fake_dashboard_state() -> dict[str, object]:
    return {
        "cluster": "prod-eu-core",
        "database": "customer_ledger",
        "build": f"2026.05.{randint(10, 24)}",
        "open_alerts": randint(2, 9),
        "replication": choice(["healthy", "lagging", "maintenance"]),
        "users": FAKE_USERS,
    }


def fake_secret_bundle() -> dict[str, str]:
    return {
        "note": "decoy credentials generated by Phantom-Net",
        "db_user": "backup_reader",
        "db_password": "PNET-FAKE-7f91-rotation",
        "api_token": "pnet_decoy_token_do_not_use",
    }


def fake_file_listing() -> dict[str, object]:
    return {
        "cwd": "/srv/app",
        "host": "app-prod-02",
        "files": FAKE_FILES,
    }


def fake_admin_users() -> dict[str, object]:
    return {
        "tenant": "core-enterprise",
        "users": FAKE_USERS,
        "note": "privileged account review pending",
    }


def fake_database_schema() -> dict[str, object]:
    return {
        "database": "customer_ledger",
        "engine": "PostgreSQL 14.9",
        "replica": choice(["primary", "read-replica-1", "read-replica-2"]),
        "tables": FAKE_TABLES,
    }


def fake_query_result(query: str) -> dict[str, object]:
    table = "users"
    lowered = query.lower()
    if "payment" in lowered:
        table = "payments"
    elif "api" in lowered or "key" in lowered:
        table = "api_keys"
    elif "audit" in lowered:
        table = "admin_audit_log"

    rows = {
        "users": [
            {"id": 1001, "email": "admin@corp.example", "password_hash": "$2b$12$decoy", "mfa_secret": "PNET-FAKE"},
            {"id": 1002, "email": "backup@corp.example", "password_hash": "$2b$12$archive", "mfa_secret": "disabled"},
        ],
        "payments": [
            {"id": 501, "customer_id": 9182, "card_last4": "4242", "amount": "1290.00", "status": "settled"},
            {"id": 502, "customer_id": 9271, "card_last4": "1881", "amount": "84.20", "status": "review"},
        ],
        "api_keys": [
            {"id": 7, "owner": "backup_svc", "token_prefix": "pnet_live_decoy_", "scope": "read:all"},
            {"id": 11, "owner": "admin", "token_prefix": "pnet_admin_decoy_", "scope": "admin"},
        ],
        "admin_audit_log": [
            {"id": 901, "actor": "admin", "action": "export_users", "ip_address": "10.42.8.12"},
            {"id": 902, "actor": "backup_svc", "action": "download_backup", "ip_address": "10.42.9.17"},
        ],
    }
    return {
        "query_id": f"qry_{randint(10000, 99999)}",
        "status": choice(["running", "partial", "completed_with_warnings"]),
        "table": table,
        "row_count": len(rows[table]),
        "rows": rows[table],
    }


def fake_backup_catalog() -> dict[str, object]:
    return {
        "bucket": "s3://corp-prod-backups",
        "retention_days": 35,
        "backups": FAKE_BACKUPS,
    }


def fake_backup_manifest(name: str) -> dict[str, object]:
    return {
        "backup": name or "daily-prod-2026-05-23.tar.gz",
        "parts": [
            {"name": "metadata.json", "sha256": "decoy-meta-74dd", "size": "12 KB"},
            {"name": "database/customer_ledger.sql", "sha256": "decoy-ledger-a91f", "size": "3.9 GB"},
            {"name": "files/uploads.tar", "sha256": "decoy-upload-9ad2", "size": "870 MB"},
            {"name": "secrets/env.snapshot", "sha256": "decoy-env-81bc", "size": "7 KB"},
        ],
        "restore_command": f"restorectl apply --source {name or 'daily-prod-2026-05-23.tar.gz'} --target prod",
    }


def fake_slow_job(path: str) -> dict[str, object]:
    return {
        "job": f"export_{randint(1000, 9999)}",
        "path": path,
        "status": choice(["queued", "preparing", "waiting_for_replica"]),
        "estimated_seconds": randint(35, 180),
        "message": "large export staged; retry the polling endpoint shortly",
    }


def fake_ftp_listing(path: str = "/") -> dict[str, object]:
    return {
        "server": "vsftpd 3.0.5",
        "cwd": path,
        "entries": [
            {"name": "incoming", "type": "dir", "mode": "drwxr-xr-x"},
            {"name": "backups", "type": "dir", "mode": "drwx------"},
            {"name": "prod.env", "type": "file", "size": "4 KB", "mode": "-rw-------"},
            {"name": "database.dump.gz", "type": "file", "size": "1.8 GB", "mode": "-rw-r-----"},
        ],
    }


def fake_terminal_response(command: str) -> dict[str, object]:
    command = command.strip() or "help"
    responses = {
        "help": "Available commands: id, whoami, hostname, pwd, ls, cat .env, ps aux, docker ps, history",
        "id": "uid=1000(app) gid=1000(app) groups=1000(app),27(sudo)",
        "whoami": "app",
        "hostname": "app-prod-02",
        "pwd": "/srv/app/current",
        "ls": "app.py\nconfig\nbackups\n.env\nlogs\nuploads",
        "cat .env": "DB_HOST=db-prod.internal\nDB_USER=backup_reader\nDB_PASSWORD=PNET-FAKE-7f91-rotation",
        "ps aux": "root 1 0.0 supervisor\napp 231 1.2 gunicorn\npostgres 544 0.4 postgres",
        "docker ps": "CONTAINER ID IMAGE COMMAND STATUS PORTS\n91af web-api:2026.05 gunicorn Up 14 days 0.0.0.0:8080",
        "history": "1 ls\n2 cat .env\n3 pg_dump customer_ledger\n4 aws s3 ls s3://corp-prod-backups",
    }
    output = responses.get(command, f"bash: {command}: command queued but backend terminal is busy")
    return {
        "host": "app-prod-02",
        "cwd": "/srv/app/current",
        "command": command,
        "exit_code": 0 if command in responses else 127,
        "stdout": output,
    }
